"""Add opening and closing time to clinics

Revision ID: 8c4d34f622ad
Revises: 7ae2ccbad8d0
Create Date: 2025-10-31 17:50:47.036404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c4d34f622ad'
down_revision = '7ae2ccbad8d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clinics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opening_time', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('closing_time', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clinics', schema=None) as batch_op:
        batch_op.drop_column('closing_time')
        batch_op.drop_column('opening_time')

    # ### end Alembic commands ###
